Updates docker yarn run to use --production
canonical-web-and-design/jaas-dashboard pull request #1112
Opened 2021-08-11 10:25 UTC by petesfrench

## Done

- Updates docker yarn run to use --production

## QA

- Pull code
- Run `./run clean && ./run serve`
- Open http://0.0.0.0:8036/
- Check nothing is broken

2021-08-11 10:26 UTC, webteam-app commented
Demo starting at https://jaas-dashboard-1112.demos.haus

2021-08-11 14:18 UTC, hatched requested changes

2021-08-11 14:18 UTC, hatched commented on Dockerfile
> +RUN npm install -g yarn --production
This change is a noop. the `--production` flag only does something when it's installing from a package.json. You probably meant to add this to line 15 instead.

2021-08-11 14:34 UTC, hatched commented on Dockerfile
> +RUN npm install -g yarn --production
Sorry ignore that previous comment, this is still a noop but if you move it to 15 then it won't have the necessary dependencies to actually build the project :)

2021-08-12 11:23 UTC, petesfrench commented
@hatched Hi, I moved the production tag to the other line as per your suggestion and played around with the dependencies to get it to build. I think it should work fine now?

2021-08-12 15:40 UTC, hatched approved these changes

2021-08-12 15:41 UTC, hatched commented
Thanks for getting this working it's much faster to build.

After some digging the reason these random deps had to be moved up is because CRA runs lint on build.

2021-08-12 15:41 UTC, merged