Add support for relative controller api endpoint paths.
canonical-web-and-design/jaas-dashboard pull request #1152
Opened 2021-09-29 21:40 UTC by hatched

## Done

Added support for relative controller API endpoint paths. This is necessary because the charm can provide a relative path when it's proxying the connections to the same host. This allows the dashboard to connect to the correct endpoint even when we don't know the ultimate endpoint of the proxy.

## QA

- The app should continue to work as expected.

2021-09-29 21:40 UTC, webteam-app commented
Demo starting at https://jaas-dashboard-1152.demos.haus

2021-09-30 06:29 UTC, anthonydillon commented on src/index.js
> +  if (controllerAPIEndpoint.indexOf("://") === -1) {
Can you use `includes`? It's clearer.

2021-09-30 06:31 UTC, anthonydillon requested changes
Simple suggestion in the code. Should there be a test for this?

2021-10-01 15:28 UTC, hatched commented on src/index.js
> +  if (controllerAPIEndpoint.indexOf("://") === -1) {
Good call.

2021-10-01 16:14 UTC, hatched commented
There should definitely be some tests, unfortunately this file isn't tested at all so we'll have to swing back around and add some.

2021-10-01 17:10 UTC, jpmartinspt approved these changes

2021-10-01 17:12 UTC, merged