MVP to render the cross model relations and offers
canonical-web-and-design/jaas-dashboard pull request #693
Opened 2020-09-24 21:42 UTC by hatched

## Done

As the data and designs are in flux for this feature this is an MVP to get the CMR and Offers rendered to the details pages.

## QA

- Follow [cmr-scenario-1 docs](https://juju.is/docs/cmr-scenario-1) to setup an environment with cross model relations
- Follow [developing while connected to a Juju controller](https://github.com/canonical-web-and-design/jaas-dashboard#developing-while-connected-to-a-juju-controller) to connect your local running instance of the dashboard to the remove environment created above.

## Details

Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1215

## Screenshots
![Screen Shot 2020-09-24 at 3 19 02 PM](https://user-images.githubusercontent.com/532033/94203012-f8fd3e00-fe7b-11ea-92ab-8eae15826644.png)
![Screen Shot 2020-09-24 at 3 28 55 PM](https://user-images.githubusercontent.com/532033/94203014-fa2e6b00-fe7b-11ea-982d-67af9076c090.png)
![Screen Shot 2020-09-24 at 3 30 45 PM](https://user-images.githubusercontent.com/532033/94203018-fb5f9800-fe7b-11ea-9014-fd171b6f4232.png)
![Screen Shot 2020-09-24 at 3 31 01 PM](https://user-images.githubusercontent.com/532033/94203019-fb5f9800-fe7b-11ea-8af0-b33a50551567.png)

2020-09-24 21:42 UTC, webteam-app commented
Demo starting at https://jaas-dashboard-693.demos.haus

2020-09-25 14:32 UTC, spencerbygraves commented
@hatched is it possible to align the columns a bit better please?

For example:

- Status, Workload, State, Requirer
- Version, Agent, AZ, Interface, Endpoints
- Store, Public address, Instance ID, Type
- OS, Message, Connections

Thanks

![image](https://user-images.githubusercontent.com/9105999/94279603-3fb66b00-ff44-11ea-9169-643583c26e86.png)

2020-09-28 16:49 UTC, hatched commented
Thanks @spencerbygraves I've created a [follow-up issue](https://github.com/canonical-web-and-design/jaas-dashboard/issues/700) to address that as it's a bit of work and out of scope for this PR. Mind taking another look at the review?

2020-09-28 17:04 UTC, anthonydillon requested changes
Code looks good, one hardcoded issue.

2020-09-28 17:04 UTC, anthonydillon commented on src/pages/Models/Details/generators.js
> +              {offer.applicationName}:db
This will render duplicate charms but that is ok for this pass

2020-09-28 17:36 UTC, anthonydillon approved these changes
QA is good just the hardcoded issue in the code.

2020-09-28 20:57 UTC, merged