Use event listener hook
canonical-web-and-design/jaas-dashboard pull request #731
Opened 2020-10-27 10:01 UTC by barrymcgee

## Done

Move complexity around event listeners in useEffects into a custom hook where instantiation and cleanup are abstracted away.

## QA

- Pull code
- Run `./run clean && ./run serve`
- Open http://0.0.0.0:8036/
- Ensure all tests pass
- Check code

2020-10-27 10:01 UTC, webteam-app commented
Demo starting at https://jaas-dashboard-731.demos.haus

2020-10-27 16:40 UTC, hatched requested changes
`Output.js` and `useOffline.js` also use `addEventListener` and can take advantage of this.

2020-10-28 14:10 UTC, barrymcgee commented
As discussed in Mattermost with @hatched .. 

- useOffline doesn't use it because I think custom hooks shouldn't depend on each other
- Output doesn't use it because of complexity (and possible bug) in cleanup

2020-10-28 16:36 UTC, hatched approved these changes

2020-10-28 16:38 UTC, merged