WIP: Panels to pages
canonical-web-and-design/jaas-dashboard pull request #896
Opened 2021-03-02 14:38 UTC by barrymcgee

Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1624,
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1621,
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1623,
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1625,
Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1628,

2021-03-02 14:38 UTC, webteam-app commented
Demo starting at https://jaas-dashboard-896.demos.haus

2021-03-04 12:59 UTC, barrymcgee commented on src/components/ChipGroup/ChipGroup.tsx
> +              // @ts-ignore Can't seem to apply type Chip to [label,count] above?
@hatched Let's chat about this.

2021-03-04 13:08 UTC, barrymcgee commented on src/layout/BaseLayout/BaseLayout.test.tsx
> +    // @ts-ignore sideNavCollapsed doesn't appear on type '{ userMenuActive: boolean; }'?
@hatched Let's talk about this.

2021-03-04 14:30 UTC, long-chung commented
Really great work. 
One minor comment, could you adopt the same styling as Ant did for the models segment control please. i.e all the segments should be the same width as the one with the longest text.
<img width="185" alt="Screenshot 2021-03-04 at 14 27 21" src="https://user-images.githubusercontent.com/68847062/109978760-1f11ee80-7cf6-11eb-8e4f-0d42e4c78d87.png">
<img width="307" alt="Screenshot 2021-03-04 at 14 27 37" src="https://user-images.githubusercontent.com/68847062/109978777-220cdf00-7cf6-11eb-8a36-41c2f8c49928.png">

2021-03-08 15:32 UTC, hatched requested changes

2021-03-08 15:32 UTC, hatched commented on src/pages/EntityDetails/counts.js
> +      return null;
this should probably just have a `break;` here and then chips will be returned as null.

2021-03-08 15:32 UTC, hatched commented on src/pages/EntityDetails/EntityDetails.js
> +  if (modelName !== modelStatusData?.model?.name) {
This makes it impossible to access a model before the application has had a chance to actually load the model data. To reproduce view a model then an app then refresh, it'll 404.

2021-03-08 16:25 UTC, hatched approved these changes
Thanks for all this work!

2021-03-08 16:27 UTC, merged