WIP: Panel improvements
canonical-web-and-design/jaas-dashboard pull request #916
Opened 2021-03-10 15:22 UTC by barrymcgee

## Done

- Remove duplicate `<main>` element from Login component
- Stop panel form overflowing
- Add back the panel box shadow
- Close panel when escape key is clicked

## QA

- Pull code
- Run `./run clean && ./run serve`
- Open http://0.0.0.0:8036/
- Verify as above

2021-03-10 15:22 UTC, webteam-app commented
Demo starting at https://jaas-dashboard-916.demos.haus

2021-03-12 02:59 UTC, hatched requested changes

2021-03-12 02:59 UTC, hatched commented on src/components/LogIn/LogIn.js
> +      <div className="main">{children}</div>
maybe a more appropriate class name would be something like `app-content` ?

2021-03-12 02:59 UTC, hatched commented on src/panels/panels.tsx
> +    close.onEscape(e, setPanelQs)
I'm not sure we should land this escape code as-is as we know it's going to cause issues right away if the panel content cannot prevent it from happening. 

I'd prefer it to not close on escape until we have an implementation that is cancellable.

2021-03-12 15:49 UTC, barrymcgee commented on src/panels/panels.tsx
> +  const closeOnEscape = (e: KeyboardEvent) => {
Done

2021-03-15 16:30 UTC, hatched approved these changes

2021-03-15 16:31 UTC, merged