Add interactivity to selecting an action in the Actions panel
canonical-web-and-design/jaas-dashboard pull request #926
Opened 2021-03-18 04:20 UTC by hatched

## Done

The actions list is now styled to match the designs.
- Selecting an action opens the actions option list (if one exists)
- If an option description is longer than 30 characters it'll be collapsed and allow for expansion.

TODO:
- Animate the selected action open to reveal the option list.
- Animate the description open.

## QA

- Pull code
- Run `./run clean && ./run serve`
- Open http://0.0.0.0:8036/
- View a charm with actions, select an action and see the available interactions

## Details

Fixes https://github.com/canonical-web-and-design/juju-squad/issues/1663

## Screenshots

![Screen Shot 2021-03-17 at 8 52 41 PM](https://user-images.githubusercontent.com/532033/111572824-fca8b800-876e-11eb-8919-1487bddc43c4.png)

2021-03-18 04:21 UTC, webteam-app commented
Demo starting at https://jaas-dashboard-926.demos.haus

2021-03-18 20:40 UTC, hatched commented on src/components/RadioInputBox/RadioInputBox.tsx
> +    const animation = wrapper.animate(
This is using [WAAPI](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API/Web_Animations_API_Concepts) so it's still as performant as doing it in CSS but this actually works 😆

2021-03-18 21:08 UTC, anthonydillon requested changes
This looks good. Can you add some tests to the new element. 

There are a bunch of Vanilla patterns that could be used here. Such as required form elements, etc. But they can be cleaned up after.

2021-03-18 22:29 UTC, anthonydillon approved these changes
LGTM :+1:

2021-03-19 14:12 UTC, hatched commented
Thanks all

2021-03-19 14:12 UTC, merged